[package]
name = "bazaar-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = "2.0"
tokio = { version = "1", features = ["full"] }
bson = "2.0"
futures-util = "0.3" # futures-util bağımlılığı
